In [ ]:
#1 Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.



In [4]:
import numpy as np


array = np.arange(1, 11)

# Reshape the array to a 2x5 matrix
matrix = array.reshape(2, 5)

# Print the matrix
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#2 Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [6]:
import numpy as np

# Create a NumPy array with numbers from 1 to 20
array = np.arange(1, 21)

# Extract elements between the 5th and 15th index
extracted_elements = array[5:15]

# Print the extracted elements
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
#3 Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [16]:
import pandas as pd

# Create a Pandas series
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)

# Add a new item to the series
series['pears'] = 4

series


apples     3
bananas    2
oranges    1
pears      4
dtype: int64

In [ ]:
#4 Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [59]:
import pandas as pd
data = {
    'name' : ['Abin','Abinu','Abu','Adam','Mazood','kureshi','Jathin','Rick','Priyadashini','jathin'],
    'age' : [23,43,24,45,27,67,86,43,23,45],
    'gender': ['M','M','M','M','M','M','M','M','M','M']
}
data= pd.DataFrame(data)
print(data)


           name  age gender
0          Abin   23      M
1         Abinu   43      M
2           Abu   24      M
3          Adam   45      M
4        Mazood   27      M
5       kureshi   67      M
6        Jathin   86      M
7          Rick   43      M
8  Priyadashini   23      M
9        jathin   45      M


In [ ]:
#5  Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.



In [61]:
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
data['occupation'] = occupations

print("DataFrame with Occupation Column:\n", data)

DataFrame with Occupation Column:
            name  age gender  occupation
0          Abin   23      M  Programmer
1         Abinu   43      M     Manager
2           Abu   24      M     Analyst
3          Adam   45      M  Programmer
4        Mazood   27      M     Manager
5       kureshi   67      M     Analyst
6        Jathin   86      M  Programmer
7          Rick   43      M     Manager
8  Priyadashini   23      M     Analyst
9        jathin   45      M  Programmer


In [ ]:
#6 Select the rows of the dataframe where the age is greater than or equal to 30.


In [63]:
age = data[data['age'] >= 30]
print("Rows where age >= 30:\n", age)

Rows where age >= 30:
       name  age gender  occupation
1    Abinu   43      M     Manager
3     Adam   45      M  Programmer
5  kureshi   67      M     Analyst
6   Jathin   86      M  Programmer
7     Rick   43      M     Manager
9   jathin   45      M  Programmer


In [ ]:
#7 Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [67]:
data.to_csv('output.csv', index=False)

# Read the CSV file
read_data = pd.read_csv('output.csv')
# Display the contents
print("DataFrame from CSV:\n", read_data)

DataFrame from CSV:
            name  age gender  occupation
0          Abin   23      M  Programmer
1         Abinu   43      M     Manager
2           Abu   24      M     Analyst
3          Adam   45      M  Programmer
4        Mazood   27      M     Manager
5       kureshi   67      M     Analyst
6        Jathin   86      M  Programmer
7          Rick   43      M     Manager
8  Priyadashini   23      M     Analyst
9        jathin   45      M  Programmer
